# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreaderuser',
            name='password',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookreaderuser',
            name='username',
            field=models.CharField(default=2, max_length=60, unique=True),
            preserve_default=False,
        ),
    ]

