# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 14:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0002_auto_20161224_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreaderuser',
            name='django_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]

