# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 14:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0003_auto_20161224_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreaderuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='bookreaderuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='bookreaderuser',
            name='django_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]

