# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0004_auto_20161224_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(default='author', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='translator_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
