# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 21:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('showSomeResult', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topgenre',
            name='adding_date',
        ),
        migrations.AddField(
            model_name='bookfortarjome',
            name='adding_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 3, 21, 52, 13, 814687, tzinfo=utc), verbose_name='date added'),
        ),
    ]
