# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 21:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('showSomeResult', '0002_auto_20170104_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookfortarjome',
            name='adding_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 3, 21, 53, 58, 636952, tzinfo=utc), verbose_name='date added'),
        ),
    ]
